using FeedlotApp.Models;

namespace FeedlotApp.Views
{
    public partial class BookingListPage : ContentPage
    {
        public BookingListPage()
        {
            InitializeComponent(); // this is generated by the XAML compiler
            LoadBookings();
        }

        private async void LoadBookings()
        {
            var bookings = await App.FLDatabase.GetAllBookingsAsync();
            BookingCollectionView.ItemsSource = bookings;
        }
    }
}
